version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  pre_build:
    commands:
      - echo Nothing to do in the pre-build phase

  build:
    commands:
      - echo Build started on `date`
      - mvn install
  
  post_build:
    commands:
      - echo Build completed on `date`
      - yum install git -y
      - yum install zip -y
      - yum install aws-cli -y
      - aws s3 cp s3://dgruploads-bucket/ . --recursive
      - mkdir scripts
#      - ls -l
      - cp copy.sh install_tomcat.sh start.sh stop.sh scripts
      - zip -r hello-world-web-app.zip appspec.yml scripts/ target/hello-world-web-app.war
      - aws s3 cp hello-world-web-app.zip s3://dgruploads-bucket
artifacts:
  files:
    - target/hello-world-web-app.war
